version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: lecture
      MYSQL_USER: lecture
      MYSQL_PASSWORD: 123
      TZ: Asia/Seoul
